services:
  - type: web
    name: esp32-cam-viewer
    runtime: static
    buildCommand: ""
    staticPublishPath: ./src
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
